stages:
  - build
  - test

build_script:
  stage: build
  script:
    - python3 main.py  # Run main.py to generate the .db file
    - ls -la  # List files to verify the .db file is created
    - cat week5_project.db  # Ensure the .db file exists and is usable
  artifacts:
    paths:
      - week5_project.db  # Store the database file as an artifact to use in the test stage

test_script:
  stage: test
  script:
    - python3 -m unittest test_main.py  # Run the unit tests using the .db file
